name: Apple Music Playlist Monitor

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:       # manual trigger

jobs:
  check-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          PLAYLIST_URL: ${{ secrets.PLAYLIST_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python <<EOF
          import os, hashlib, requests
          from bs4 import BeautifulSoup

          playlist_url = os.environ['PLAYLIST_URL']
          webhook_url = os.environ.get('WEBHOOK_URL')

          headers = {"User-Agent": "Mozilla/5.0"}
          response = requests.get(playlist_url, headers=headers)
          soup = BeautifulSoup(response.text, "html.parser")
          desc_element = soup.find("meta", attrs={"name": "Description"})
          description = desc_element["content"] if desc_element else "No description"

          hash_file = ".last_description_hash"
          new_hash = hashlib.sha256(description.encode()).hexdigest()

          try:
              with open(hash_file, "r") as f:
                  old_hash = f.read().strip()
          except FileNotFoundError:
              old_hash = ""

          if new_hash != old_hash:
              print("Description changed!")
              if webhook_url:
                  requests.post(webhook_url, json={"content": f"Playlist description changed: {description}"})
              with open(hash_file, "w") as f:
                  f.write(new_hash)
          else:
              print("No change.")
          EOF
