name: Apple‑Music Playlist Monitor

on:
  schedule:
    # every 10 minutes (adjust as you like)
    - cron:  '*/10 * * * *'
  workflow_dispatch:     # lets you run it manually, too

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run changedetection.io one‑off
      run: |
        docker run --rm \
          -e PLAYLIST_URL="${{ secrets.PLAYLIST_URL }}" \
          -e LAST_HASH_FILE="last_hash.txt" \
          ghcr.io/dgtlmoon/changedetection.io:latest \
          /bin/sh -c '
            apk add --no-cache curl grep;
            DESC=$(curl -s "$PLAYLIST_URL" | grep -oP "(?<=<meta property=\"og:description\" content=\")[^\"]+");
            HASH=$(echo -n "$DESC" | sha256sum | cut -d" " -f1);
            echo "Current hash: $HASH";
            if [ -f "$LAST_HASH_FILE" ]; then
              OLD=$(cat "$LAST_HASH_FILE");
              echo "Previous hash: $OLD";
            else
              OLD="";
            fi
            if [ "$HASH" != "$OLD" ]; then
              echo "Description changed!";
              echo "$HASH" > "$LAST_HASH_FILE";
              if [ -n "$WEBHOOK_URL" ]; then
                curl -X POST -H "Content-Type: application/json" \
                  --data "{\"text\":\"Apple Music playlist description updated!\"}" \
                  "$WEBHOOK_URL";
              fi
            else
              echo "No change.";
            fi
          '

    - name: Persist last hash between runs
      uses: actions/upload-artifact@v4
      with:
        name: last_hash
        path: last_hash.txt
